[Rainmeter]
Update=-1
; Move a janela 20 pixels para a direita e 40 para baixo em relação à skin principal
OnRefreshAction=[!Move "(#SkinPosX# + 20)" "(#SkinPosY# + 40)"]

[Variables]
@include=#@#SkinInfo.inc

[Background]
Meter=Shape
Shape=Rectangle 0,0,360,225,6 | Fill Color #Dark1# | StrokeWidth 1 | Stroke Color #Dark2#
DynamicVariables=1

[CloseHelp]
Meter=String
Text="[\xe8bb]"
FontFace=Segoe Fluent Icons
FontSize=10
FontColor=#TextColor#
SolidColor=0,0,0,1
X=335
Y=10
AntiAlias=1
LeftMouseUpAction=[!DeactivateConfig]
MouseOverAction=[!SetOption CloseHelp FontColor "#SettingsHover#"][!UpdateMeter CloseHelp][!ReDraw]
MouseLeaveAction=[!SetOption CloseHelp FontColor "#TextColor#"][!UpdateMeter CloseHelp][!ReDraw]

[Title]
Meter=String
Text="Shortcuts & Tips"
FontColor=#SettingsHover#
FontSize=12
FontFace=Segoe UI
StringStyle=Bold
X=180
Y=10
StringAlign=Center
AntiAlias=1

[Shortcuts]
Meter=String
Text="Middle Mouse Button : Open Search#CRLF#Right Mouse Button : Open Steam Page#CRLF#Ctrl + Space : Switch Mode (Horizontal/Vertical)#CRLF#Scroll Wheel : Navigate List#CRLF#Hover & Click Eye Icon : Hide Game"
FontColor=#TextColor#
FontSize=10
FontFace=Segoe UI
X=180
Y=40
StringAlign=Center
AntiAlias=1

[SortingInfo]
Meter=String
Text="* Note: Sorting by Playtime or Last Played#CRLF#requires a Steam API Key and Steam ID."
FontColor=#TextColor#,150
FontSize=9
FontFace=Segoe UI
X=180
Y=135
StringAlign=Center
AntiAlias=1

[ScanInfo]
Meter=String
Text="Make sure to run 'Scan for Games' to get started!"
FontColor=#SettingsHover#
FontSize=10
FontFace=Segoe UI
StringStyle=Bold
X=180
Y=185
StringAlign=Center
AntiAlias=1