[Name1]
Meter=String
Text=#ID1name#
LeftMouseUpAction=[steam://rungameid/#ID1#]
RightMouseUpAction=[steam://store/#ID1#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G1

[Game1]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID1#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID1#]
RightMouseUpAction=[steam://store/#ID1#]
Hidden=1
Group=Games | G1

[Gap1]
Meter=Image
MeterStyle=GapStyle

[Name2]
Meter=String
Text=#ID2name#
LeftMouseUpAction=[steam://rungameid/#ID2#]
RightMouseUpAction=[steam://store/#ID2#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G2

[Game2]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID2#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID2#]
RightMouseUpAction=[steam://store/#ID2#]
Hidden=1
Group=Games | G2

[Gap2]
Meter=Image
MeterStyle=GapStyle

[Name3]
Meter=String
Text=#ID3name#
LeftMouseUpAction=[steam://rungameid/#ID3#]
RightMouseUpAction=[steam://store/#ID3#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G3

[Game3]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID3#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID3#]
RightMouseUpAction=[steam://store/#ID3#]
Hidden=1
Group=Games | G3

[Gap3]
Meter=Image
MeterStyle=GapStyle

[Name4]
Meter=String
Text=#ID4name#
LeftMouseUpAction=[steam://rungameid/#ID4#]
RightMouseUpAction=[steam://store/#ID4#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G4

[Game4]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID4#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID4#]
RightMouseUpAction=[steam://store/#ID4#]
Hidden=1
Group=Games | G4

[Gap4]
Meter=Image
MeterStyle=GapStyle

[Name5]
Meter=String
Text=#ID5name#
LeftMouseUpAction=[steam://rungameid/#ID5#]
RightMouseUpAction=[steam://store/#ID5#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G5

[Game5]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID5#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID5#]
RightMouseUpAction=[steam://store/#ID5#]
Hidden=1
Group=Games | G5

[Gap5]
Meter=Image
MeterStyle=GapStyle

[Name6]
Meter=String
Text=#ID6name#
LeftMouseUpAction=[steam://rungameid/#ID6#]
RightMouseUpAction=[steam://store/#ID6#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G6

[Game6]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID6#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID6#]
RightMouseUpAction=[steam://store/#ID6#]
Hidden=1
Group=Games | G6

[Gap6]
Meter=Image
MeterStyle=GapStyle

[Name7]
Meter=String
Text=#ID7name#
LeftMouseUpAction=[steam://rungameid/#ID7#]
RightMouseUpAction=[steam://store/#ID7#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G7

[Game7]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID7#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID7#]
RightMouseUpAction=[steam://store/#ID7#]
Hidden=1
Group=Games | G7

[Gap7]
Meter=Image
MeterStyle=GapStyle

[Name8]
Meter=String
Text=#ID8name#
LeftMouseUpAction=[steam://rungameid/#ID8#]
RightMouseUpAction=[steam://store/#ID8#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G8

[Game8]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID8#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID8#]
RightMouseUpAction=[steam://store/#ID8#]
Hidden=1
Group=Games | G8

[Gap8]
Meter=Image
MeterStyle=GapStyle

[Name9]
Meter=String
Text=#ID9name#
LeftMouseUpAction=[steam://rungameid/#ID9#]
RightMouseUpAction=[steam://store/#ID9#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G9

[Game9]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID9#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID9#]
RightMouseUpAction=[steam://store/#ID9#]
Hidden=1
Group=Games | G9

[Gap9]
Meter=Image
MeterStyle=GapStyle

[Name10]
Meter=String
Text=#ID10name#
LeftMouseUpAction=[steam://rungameid/#ID10#]
RightMouseUpAction=[steam://store/#ID10#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G10

[Game10]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID10#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID10#]
RightMouseUpAction=[steam://store/#ID10#]
Hidden=1
Group=Games | G10

[Gap10]
Meter=Image
MeterStyle=GapStyle

[Name11]
Meter=String
Text=#ID11name#
LeftMouseUpAction=[steam://rungameid/#ID11#]
RightMouseUpAction=[steam://store/#ID11#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G11

[Game11]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID11#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID11#]
RightMouseUpAction=[steam://store/#ID11#]
Hidden=1
Group=Games | G11

[Gap11]
Meter=Image
MeterStyle=GapStyle

[Name12]
Meter=String
Text=#ID12name#
LeftMouseUpAction=[steam://rungameid/#ID12#]
RightMouseUpAction=[steam://store/#ID12#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G12

[Game12]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID12#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID12#]
RightMouseUpAction=[steam://store/#ID12#]
Hidden=1
Group=Games | G12

[Gap12]
Meter=Image
MeterStyle=GapStyle

[EName1]
Meter=String
Text=#Egame1#
LeftMouseUpAction=["#Egame1Path#"]
RightMouseUpAction=[!ActivateConfig "SteamyRain\ExtraManager" "Manager.ini"]
MeterStyle=NameStyle
Hidden=1
Group=Games | EG1

[EGame1]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Users\Caio Eppenstein\Desktop\peaha.jpg
LeftMouseUpAction=["#Egame1Path#"]
RightMouseUpAction=[!ActivateConfig "SteamyRain\ExtraManager" "Manager.ini"]
Hidden=1
Group=Games | EG1

[EGap1]
Meter=Image
MeterStyle=GapStyle

[EName2]
Meter=String
Text=#Egame2#
LeftMouseUpAction=["#Egame2Path#"]
RightMouseUpAction=[!ActivateConfig "SteamyRain\ExtraManager" "Manager.ini"]
MeterStyle=NameStyle
Hidden=1
Group=Games | EG2

[EGame2]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Users\Caio Eppenstein\Desktop\pasta.png
LeftMouseUpAction=["#Egame2Path#"]
RightMouseUpAction=[!ActivateConfig "SteamyRain\ExtraManager" "Manager.ini"]
Hidden=1
Group=Games | EG2

[EGap2]
Meter=Image
MeterStyle=GapStyle

