[Game1]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID1#\header.jpg
LeftMouseUpAction=[steam://rungameid/#ID1#]
RightMouseUpAction=[steam://store/#ID1#]
Hidden=#Vis1#
Group=Games | G1

[Vis1]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis1" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis1 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G1][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis1"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G1"][!Updatemeasure HiddenWindow]
Hidden=#Vis1#
Group=Games | G1

[Gap1]
Meter=Image
MeterStyle=GapStyle

[Game2]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID2#\header.jpg
LeftMouseUpAction=[steam://rungameid/#ID2#]
RightMouseUpAction=[steam://store/#ID2#]
Hidden=#Vis2#
Group=Games | G2

[Vis2]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis2" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis2 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G2][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis2"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G2"][!Updatemeasure HiddenWindow]
Hidden=#Vis2#
Group=Games | G2

[Gap2]
Meter=Image
MeterStyle=GapStyle

[Game3]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID3#\header.jpg
LeftMouseUpAction=[steam://rungameid/#ID3#]
RightMouseUpAction=[steam://store/#ID3#]
Hidden=#Vis3#
Group=Games | G3

[Vis3]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis3" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis3 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G3][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis3"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G3"][!Updatemeasure HiddenWindow]
Hidden=#Vis3#
Group=Games | G3

[Gap3]
Meter=Image
MeterStyle=GapStyle

[Game4]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID4#\header.jpg
LeftMouseUpAction=[steam://rungameid/#ID4#]
RightMouseUpAction=[steam://store/#ID4#]
Hidden=#Vis4#
Group=Games | G4

[Vis4]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis4" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis4 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G4][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis4"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G4"][!Updatemeasure HiddenWindow]
Hidden=#Vis4#
Group=Games | G4

[Gap4]
Meter=Image
MeterStyle=GapStyle

[Game5]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID5#\header.jpg
LeftMouseUpAction=[steam://rungameid/#ID5#]
RightMouseUpAction=[steam://store/#ID5#]
Hidden=#Vis5#
Group=Games | G5

[Vis5]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis5" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis5 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G5][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis5"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G5"][!Updatemeasure HiddenWindow]
Hidden=#Vis5#
Group=Games | G5

[Gap5]
Meter=Image
MeterStyle=GapStyle

[Game6]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID6#\b4f36532c943011a9f1600c2585ca7065ef5b1bb/library_header.jpg
LeftMouseUpAction=[steam://rungameid/#ID6#]
RightMouseUpAction=[steam://store/#ID6#]
Hidden=#Vis6#
Group=Games | G6

[Vis6]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis6" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis6 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G6][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis6"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G6"][!Updatemeasure HiddenWindow]
Hidden=#Vis6#
Group=Games | G6

[Gap6]
Meter=Image
MeterStyle=GapStyle

[Game7]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID7#\1ea445e044a2d5b09cfa8291350b63ebed6e5741/library_header.jpg
LeftMouseUpAction=[steam://rungameid/#ID7#]
RightMouseUpAction=[steam://store/#ID7#]
Hidden=#Vis7#
Group=Games | G7

[Vis7]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis7" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis7 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G7][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis7"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G7"][!Updatemeasure HiddenWindow]
Hidden=#Vis7#
Group=Games | G7

[Gap7]
Meter=Image
MeterStyle=GapStyle

[Game8]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID8#\51cd316b78c6a4c8c0b37cb153f9be721d68a76d/library_header.jpg
LeftMouseUpAction=[steam://rungameid/#ID8#]
RightMouseUpAction=[steam://store/#ID8#]
Hidden=#Vis8#
Group=Games | G8

[Vis8]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis8" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis8 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G8][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis8"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G8"][!Updatemeasure HiddenWindow]
Hidden=#Vis8#
Group=Games | G8

[Gap8]
Meter=Image
MeterStyle=GapStyle

[Game9]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID9#\9b046115b1663a4be2b252712328e4f6c162da68/library_header.jpg
LeftMouseUpAction=[steam://rungameid/#ID9#]
RightMouseUpAction=[steam://store/#ID9#]
Hidden=#Vis9#
Group=Games | G9

[Vis9]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis9" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis9 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G9][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis9"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G9"][!Updatemeasure HiddenWindow]
Hidden=#Vis9#
Group=Games | G9

[Gap9]
Meter=Image
MeterStyle=GapStyle

[Game10]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID10#\header.jpg
LeftMouseUpAction=[steam://rungameid/#ID10#]
RightMouseUpAction=[steam://store/#ID10#]
Hidden=#Vis10#
Group=Games | G10

[Vis10]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis10" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis10 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G10][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis10"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G10"][!Updatemeasure HiddenWindow]
Hidden=#Vis10#
Group=Games | G10

[Gap10]
Meter=Image
MeterStyle=GapStyle

[Game11]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID11#\6a15f25d43136a5c787cb24752edfbda35c68f7d/library_header.jpg
LeftMouseUpAction=[steam://rungameid/#ID11#]
RightMouseUpAction=[steam://store/#ID11#]
Hidden=#Vis11#
Group=Games | G11

[Vis11]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis11" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis11 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G11][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis11"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G11"][!Updatemeasure HiddenWindow]
Hidden=#Vis11#
Group=Games | G11

[Gap11]
Meter=Image
MeterStyle=GapStyle

[Game12]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID12#\84ba6dc3a83e3dd4c0739985edbaf2e4051f57c4/library_header.jpg
LeftMouseUpAction=[steam://rungameid/#ID12#]
RightMouseUpAction=[steam://store/#ID12#]
Hidden=#Vis12#
Group=Games | G12

[Vis12]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Vis12" 1 "#@#GamesInfo.inc"][!WriteKeyValue Variables GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))" "#@#GamesInfo.inc"][!SetVariable GameCountPLUS "(Clamp((#GameCountPLUS#-1),0,#GameCount#))"][!SetVariable Vis12 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup G12][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Vis12"][!SetVariable UpdateVar2 "GameCountPLUS"][!SetVariable UpdateVar3 "G12"][!Updatemeasure HiddenWindow]
Hidden=#Vis12#
Group=Games | G12

[Gap12]
Meter=Image
MeterStyle=GapStyle

[EGame1]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Users\Caio Eppenstein\Desktop\peaha.jpg
LeftMouseUpAction=["#Egame1Path#"]
RightMouseUpAction=[!ActivateConfig "SteamyRain\ExtraManager" "Manager.ini"]
Hidden=#Egame1Vis#
Group=Games | EG1

[EVis1]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Egame1Vis" 1 "#@#NonSteamGames.inc"][!WriteKeyValue Variables ExtraGameCountPLUS "(Clamp((#ExtraGameCountPLUS#-1),0,#ExtraGamesCount#))" "#@#NonSteamGames.inc"][!SetVariable ExtraGameCountPLUS "(Clamp((#ExtraGameCountPLUS#-1),0,#ExtraGamesCount#))"][!SetVariable Egame1Vis 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup EG1][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Egame1Vis"][!SetVariable UpdateVar2 "ExtraGameCountPLUS"][!SetVariable UpdateVar3 "EG1"][!Updatemeasure HiddenWindow]
Hidden=#Egame1Vis#
Group=Games | EG1

[EGap1]
Meter=Image
MeterStyle=GapStyle

[EGame2]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Users\Caio Eppenstein\Desktop\pasta.png
LeftMouseUpAction=["#Egame2Path#"]
RightMouseUpAction=[!ActivateConfig "SteamyRain\ExtraManager" "Manager.ini"]
Hidden=#Egame2Vis#
Group=Games | EG2

[EVis2]
Meter=String
MeterStyle=VisStyle
LeftMouseUpAction=[!WriteKeyValue Variables "Egame2Vis" 1 "#@#NonSteamGames.inc"][!WriteKeyValue Variables ExtraGameCountPLUS "(Clamp((#ExtraGameCountPLUS#-1),0,#ExtraGamesCount#))" "#@#NonSteamGames.inc"][!SetVariable ExtraGameCountPLUS "(Clamp((#ExtraGameCountPLUS#-1),0,#ExtraGamesCount#))"][!SetVariable Egame2Vis 1][!UpdateMeasure HideGame][!Updatemeasure Lenght][!HideMeterGroup EG2][!UpdateMeterGroup Games][!ReDraw][!SetVariable UpdateVar "Egame2Vis"][!SetVariable UpdateVar2 "ExtraGameCountPLUS"][!SetVariable UpdateVar3 "EG2"][!Updatemeasure HiddenWindow]
Hidden=#Egame2Vis#
Group=Games | EG2

[EGap2]
Meter=Image
MeterStyle=GapStyle

